### ISSUE TITLE
Allow arbitrary enums

### ISSUE THREAD

**Issue by RReverser** [dtolnay/serde-repr#6]
[RFC 2363](https://github.com/rust-lang/rfcs/pull/2363) allows to set custom discriminant on arbitrary enums with payloads, and not just C-like enums.

~~While it's currently a nightly-only feature~~ It's a stable feature since Rust 1.56, it would be great to support arbitrary enums in serde-repr too.

**Comment by pythonesque** [comment]
If possible, what would be great is for the discriminant to actually be passed as the variant index to crates like bincode, since this is the only way to keep serialized values "backwards compatible" when variants are removed (in the sense that variants that weren't removed will still be parsed correctly).  Of course, this is dependent on the particular serializer/deserializer you use.

**Comment by RReverser** [comment]
> this is dependent on the particular serializer/deserializer you use

Not only - another problem is that variant index in Serde API is limited to `u32` which won't fit all possible enum reprs, and won't allow to disambiguate between different repr types.

**Comment by pythonesque** [comment]
That is true, but for repr(u32) or less it would surely work :)

**Comment by elpiel** [comment]
What about using custom attribute macros? I would love to work on something like this.
This is especially useful in our case since the protocol we're implementing usually uses a value for the Enum encoded in e.g. `u8`, `u16`, etc. but contain additional data that is also serialized/deserialized and we need this to work with any arbitrary Enum but also include way to specify a custom discriminant.

**Comment by lokegustafsson** [comment]
This seems somewhat relevant to my use case: I want to deserialize json that looks like this:
```json
{
  "type": 5,
  "data": { ... }
}
```
Where the value of `"type"` determines which enum variant `"data"` should be parsed as. This is essentially the serde adjacently tagged container attribute, only with an integer instead of a string. Is this currently possible using this or with just serde?

**Comment by elpiel** [comment]
@lokegustafsson this is the exact thing we are looking to solve.
I've opened a WIP PR and would love to get some help with how to implement this :sweat_smile:

**Comment by ByteAlex** [comment]
This feature has been stabilized in rust 1.56, are there any updates on whether or when this will be supported by either serde or serde-repr?
The linked PR #11 is stale. :/

**Comment by dtolnay** [comment]
I would prefer if someone else would make a different crate for this use case. I am not interested in building support for this into this crate.

**Comment by RReverser** [comment]
That's a shame, this crate seems like the most natural fit since they're not too different from other discriminants.
